# REMOVE THIS
themesDir = "../../"

# DO NOT REMOVE THIS
theme = "just-me"      # use theme locally
# theme = "github.com/jota-ele-ene/just-me" # use theme as hugo module

# Just me! only renders the homepage, no section or other kinds
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

# Override these settings with your own
baseURL = "https://example.com"
languageCode = "en-us"
title = "Just me: Example Site"

[params]
  author = "John Doe"
  author_link = "#"
  ga_tracking_id = ""
